### ISSUE TITLE
Upgrading from alpha 1 to latest beta, Fira font-config

### ISSUE THREAD

**Issue by stnor** [mathjax/MathJax-src#1009]
Hi Davide,
I'm trying to upgrade my code to beta.4 from alpha.1, and I am having trouble with the font configuration.
What should I replace the two commented-out lines with please?

Thanks!

Deps:
````
    "mathjax-fira-font": "1.0.0-beta.1",
    "mathjax-full": "4.0.0-beta.4",
````

Code:
````
        const {browserAdaptor} = await import("mathjax-full/mjs/adaptors/browserAdaptor");
        const handler = await import("mathjax-full/mjs/handlers/html.js");
        handler.RegisterHTMLHandler(browserAdaptor());
        const {mathjax} = await import("mathjax-full/mjs/mathjax");
        const {MathML} = await import("mathjax-full/mjs/input/mathml");
        const {CHTML} = await import("mathjax-full/mjs/output/chtml");
//        const {MathJaxFiraFont} = await import("mathjax-fira-font/js/output/fonts/mathjax-fira/chtml");
//        const font = new MathJaxFiraFont({fontURL: '/assets/mathjax-fonts'});
        const  mathJaxDoc = mathjax.document(window.document, {
            InputJax: new MathML(),
            OutputJax: new CHTML({font: font})
        });
````

**Comment by stnor** [comment]
I think I figured out the configuration:

Is this correct? It seems to work anyway:
````
        const {MathJaxFiraFont} = await import("mathjax-fira-font/js/chtml");
        const mathJaxDoc = mathjax.document(window.document, {
            InputJax: new MathML(),
            OutputJax: new CHTML({fontData: MathJaxFiraFont, fontURL: '/assets/mathjax-fonts'})
        });
````

I get a formatting issue though, even in this simple example (the width of the `mjx-break`):

![Screenshot 2023-10-30 at 11 41 01](https://github.com/mathjax/MathJax-src/assets/561167/ebd28a4d-853e-4f59-98eb-c4dff7b23b51)

I didn't replace for webfonts, should I?

**Comment by dpvc** [comment]
Did you update your mathjax-fira-font to version 4.0.0-beta.4 (rather than 1.0.0-beta.1 that you list in your dependencies above)?  That is important, as there have been changes in the layout and fonts included (and that affects the spacing for the breakpoints).  And have you moved those fonts to your `assets/mathjax_fonts` directory?  In particular, is there `mjx-fira-brk.woff` in that directory?  Does your console show any errors about font files not being able to be loaded?

I don't know if your code is meant to be an ESM or a CommonJS file, but if it is ESM, then you can use

``` js
import {browserAdaptor} from "mathjax-full/mjs/adaptors/browserAdaptor";
```

rather than

``` js
const {browserAdaptor} = await import("mathjax-full/mjs/adaptors/browserAdaptor");
```

and similarly for the other imports.  But this is not critical.

**Comment by stnor** [comment]
Thanks a lot!
I imported the wrong version of the fira font as you pointed out, so that fixed the layout issue.

I use `await import` since I want to load mathjax lazily in my Angular (16) app to keep the bundle size down, as it's only used in a few components.

**Comment by dpvc** [comment]
OK, glad it was an easy fix.  Thanks for the info on `import`.  That makes sense.
