### ISSUE TITLE
How can I run 'npm run compile' on branch develop?

### ISSUE THREAD

**Issue by guoyutao** [mathjax/MathJax-src#1118]
How can I run 'npm run compile' on branch develop?

when i run 'npm run compile', there is an error :
develep tool: VSCode
![image](https://github.com/mathjax/MathJax-src/assets/11513385/6f33a6be-abb9-4fb6-9e0c-d502a75416a7)

**Comment by dpvc** [comment]
PS, I'm in the process of writing a response to your other issue, and was going to include a MathJax configuration that would include a patch for the problem, so if you re recompiling because of that, you might want to wait and see if using the patch is easier for you.

Also, you would need to use the `issue3252` branch, not the `develop` branch, as that PR hasn't been merged yet.

**Comment by guoyutao** [comment]
Thank you very much.
