### ISSUE TITLE
[SVG] svg root has less whitespace than in v2

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#187]
I've noticed that v3's SVG output has noticeably tighter output than v2.

Here's `$$\mathbb{Q}$$` in v2

![v2](https://user-images.githubusercontent.com/426686/51323569-e0af0c00-1a68-11e9-8376-5320bc52719e.png)

Here's v3 

![v3](https://user-images.githubusercontent.com/426686/51323570-e147a280-1a68-11e9-8f63-a11a1268de67.png)

This adds a lot of noise in visual regression testing.

I'm wondering if this only happens at the top level and if there's a way to estimate the difference.

**Comment by dpvc** [comment]
Yes, it is only at the top level, and the difference should be 2 pixels.  Version 2 added a little space at top and bottom of the outermost element in order to try to prevent the SVGs in adjacent lines of a paragraph from bumping into each other.  For example, if one line has a descender like a "j" and the next line has a superscript like "x^2", these could touch each other if the line spacing is small.

This cause other problems, however, so I removed it in v3, leaving it to page authors to add the space if they want (rather than forcing it as in v2).  An extension could easily be made to add it automatically again.

**Comment by pkra** [comment]
Thanks for clarifying, Davide.

> This cause other problems, however, so I removed it in v3, leaving it to page authors to add the space if they want (rather than forcing it as in v2)

:+1:  I like this decision since the only drawback is that it leaves a standard web design issue for the author to solve (which will be rare anyway, I think).

**Comment by dpvc** [comment]
It seems like having an enlarged `line-height` is rather popular now, and that is one way around the issue, so even if it occurs, it is not that hard to work around even by a non-programmer.

**Comment by pkra** [comment]
Right, that's what I had in mind as well.
