### ISSUE TITLE
[svg] colspan, rowspan

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#196]
Is there any chance v3's SVG output could have colspan and rowspan support?

**Comment by dpvc** [comment]
It is something that I'd like to do, but it will not be in the initial release of v3.  It may not seem like it, but this considerably complicates the table layout algorithm, and since that is already pretty complicated as it is, I have not put the time into implementing it.  

It is not just a matter of figuring out the size of the rows and columns and making one cell cover both, for example, since the spanning cell may be wider than the sum of the two columns, and so those columns need to be enlarged.  Since spanning cells can overlap (in different rows, say), how this extra space is distributed over the columns is complicated.  It is even possible to have a table where *all* the cells are spanning cells.  Mixing all that with the various column width possibilities (fixed size, `auto` sized, percentage size, `fit` sized, equal sized) together with sizing of the table as a whole (fixed size, percentage size, auto size) makes for a large number of interactions that have to be handled.  It's a messy prospect.
