### ISSUE TITLE
[TeX] change rlap / llap to expect text mode 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#208]
In TeX, rlap and llap switch to text mode, in MathJax they stay in math mode. It would be very useful for real TeX content if MathJax would align more with TeX here.

**Comment by dpvc** [comment]
In the early days, MathJax's `tex2jax` extension did not handle nested math-mode inside text-mode inside math-mode, so `$xyz\llap{$abc$}}$` would not be processed, so it would be difficult to have to convert from text-mode to math-mode inside `\llap` or `\rlap`.  Also, since MathJax doesn't support much of text-mode anyway, it seemed unnecessary to have to force people to go into text-mode and back out to math mode.

There have been discussions about having a more LaTeX-compatible configuration.  I could see an extension that removes these kinds of differences.  One of the other similar differences is with `\raise` and `\lower`, which (in actual TeX) require the item to be raised or lowered to be a box (`\hbox` or `\vbox`).  MathJax will raise or lower anything, but if its an `\hbox`, that is perfectly fine, so this isn't as an incompatibility of the same degree, but it does not produce errors when TeX would.  So that is another area where a LaTeX-compatibility extension could be useful.

Such an extension would include

```
MathJax.Hub.Register.StartupHook("TeX Jax Ready", function () {
  var MML = MathJax.ElementJax.mml;
  MathJax.InputJax.TeX.Parse.Augment({
    Lap: function (name) {
      var mml = this.InternalMath(this.GetArgument(name),0);
      mml = MML.mpadded.apply(MML,mml).With({width: 0});
      if (name === "\\llap") {mml.lspace = "-1width"}
      this.Push(MML.TeXAtom(mml));
    }

  });
});
```

to make `\llap` and `\\rlap` do as you request.  It would also load the `color` extension to make `\color` use the LaTeX syntax.

**Comment by dpvc** [comment]
Sorry, I answered this thinking it was in the v2 repository.  I see it is in v3.  So the code above won't do it.  A LaTeX-compatibility mode would still be nice (or a v2-compaitibility mode).
