### ISSUE TITLE
[SVG] Safari compatibility

### ISSUE THREAD

**Issue by uetchy** [mathjax/MathJax-src#306]
Safari does not display SVG generated from MathJax v3 while Chrome and Firefox can handle it.

## Reproducible example
[![Edit MathJax v3](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mathjax-v3-vwffw?fontsize=14)

## Version
- Safari 12.1.1
- macOS Mojave

**Comment by dpvc** [comment]
It turns out that WebKit has problems serializing namespaces attributes like `xlink:href`, and so the links from the `use` elements to their actual paths are not being made when you serialize the SVG element and then repairs it with `innerHTML`.

I have a patch that fixes the issue, so it will be fixed in the official 3.0.0 release.

In the meantime, however, there are several possible ways to work around this.  The easiest is to use

```
      OutputJax: new SVG({fontCache: 'none'})
```

which turns off the font cache, so explicit paths will be used rather than `use` elements.

Alternatively, depending on what you are actually trying to accomplish, you could avoid the serialization and simply append the SVG element into the page directly.  Simply use

```
      const math = html.math.pop();
      resolve(math);
```

in your `tex2svg()` function, and then use 

```
  document.querySelector("#app").appendChild(math);
```

to add it to the page.  This is more efficient than serializing the SVG element and then re-parsing that serialized string again.

-----

I also have several suggestions about your code example.  First, as of beta.4, there is a `convert()` function that does the compile/typeset operation for you, so you don't have to make a new document containing the math, and call the processing functions by hand.  So you can use

```
function tex2svg(equation) {
  return new Promise((resolve, reject) => {
    const adaptor = chooseAdaptor();
    RegisterHTMLHandler(adaptor);

    const html = MathJax.document('', {
      InputJax: new TeX(),
      OutputJax: new SVG({fontCache: 'none'})
    });

    MathJax.handleRetriesFor(() => {
      const math = html.convert(equation, {display: false});
      resolve(adaptor.innerHTML(math));
    }).catch(err => reject(err));
  });
}
```

Also, you don't really need to create a new document and adaptor for each equation, and you should **not** register the HTML handler more than once, so you can move that code outside your `tex2svg()` function:

```
const adaptor = chooseAdaptor();
RegisterHTMLHandler(adaptor);

const html = MathJax.document('', {
  InputJax: new TeX(),
  OutputJax: new SVG({fontCache: 'none'})
});

function tex2svg(equation) {
  return new Promise((resolve, reject) => {
    MathJax.handleRetriesFor(() => {
      const math = html.convert(equation, {display: false});
      resolve(adaptor.innerHTML(math));
    }).catch(err => reject(err));
  });
}
```

Of course, `MathJax.handleRetriesFor` returns a Promise itself, so there is no real need to create a new one:

```
function tex2svg(equation) {
  return MathJax.handleRetriesFor(() => {
    return adaptor.innerHTML(html.convert(equation, {display: false}));
  });
}
```

or even simpler

```
function tex2svg(equation) {
  return MathJax.handleRetriesFor(() =>
     adaptor.innerHTML(html.convert(equation, {display: false})})
  );
}
```

On the other hand, your configuration does involve any asynchronous operations within MathJax, so you don't really need the promise-based version at all, as it can run synchronously:

```
function tex2svg(equation) {
  return adaptor.innerHTML(html.convert(equation, {display: false}));
}
```

In that case, you don't need to use `async` and `await`.  So a complete (reduced) version of your example would be:

```
import { MathJax } from "mathjax3";
import { TeX } from "mathjax3/mathjax3/input/tex";
import { SVG } from "mathjax3/mathjax3/output/svg";
import { RegisterHTMLHandler } from "mathjax3/mathjax3/handlers/html";
import { chooseAdaptor } from "mathjax3/mathjax3/adaptors/chooseAdaptor";

const adaptor = chooseAdaptor();
RegisterHTMLHandler(adaptor);

const html = MathJax.document('', {
  InputJax: new TeX(),
  OutputJax: new SVG({fontCache: 'none'})
});

function tex2svg(equation) {
  return adaptor.innerHTML(html.convert(equation, {display:false}));
}

const math = tex2svg("\\sum^N_i x_i+y_i");
console.log(math);
document.querySelector("#app").innerHTML = math;
```

**Comment by uetchy** [comment]
@dpvc Thank you for patching bug and also reviewing my code! It helped a lot because example codes look outdated against the master branch and nowhere to find the document about this.
Maybe I'd send some PR to keep examples fresh.

**Comment by dpvc** [comment]
>  example codes look outdated against the master branch and nowhere to find the document about this.

See the [browser examples](https://github.com/mathjax/mj3-demos) and [node examples](https://github.com/mathjax/mj3-demos-node) for coding examples with descriptions and some documentation.  There are links to these in the [README](https://github.com/mathjax/mathjax-v3/tree/beta.4/README.md) of the [beta.4](https://github.com/mathjax/mathjax-v3/tree/beta.4) branch.  Note that the master branch is not the same as the beta branch.

**Comment by uetchy** [comment]
sorry but I meant `/samples` in `beta.4` (since running some examples within `beta.4` branch cause error)
And now I got that mj3-demos-node and mj3-demos are the best resources to look at first.
Thank you!
Safe to close.

**Comment by dpvc** [comment]
The samples directory dates back to when we first started the MathJax v3 rewrite, and did give some early examples of how to use MathJax v3, but it ended up becoming the place where we put files use for testing MathJax functionality instead.  It will be removed before the final release (or rather moved to a new repository for development tools).  The mj3-demos and mj3-demos-node repositories are the actual examples for people who are trying to use MathJax v3.
