### ISSUE TITLE
V3 doesn't compile

### ISSUE THREAD

**Issue by ShaMan123** [mathjax/MathJax-src#342]
### I can't get mathjax to compile.

I followed the guide [Using MathJax Components in node applications](https://github.com/mathjax/MathJax-src#using-mathjax-components-in-node-applications) with no success. 

Inner file paths are wrong and point to nowhere, `ts` files point to `js` files, **a complete mess**.

There's no documentation/example regarding the inner structure and usage of the `ts` dir here or in [MathJax-demos-node](https://github.com/mathjax/MathJax-demos-node) making it rather difficult to make a PR or workaround.

**Comment by dpvc** [comment]
> I can't get mathjax to compile.

If you mean that doing

```
npm run compile
```

produces typescript errors, then it would be helpful to report what those errors are.  If, however, you mean that the example in the section you link to doesn't run, that is a different story.  The `mathjax` npm package is already compiled, so you should not have to compile it yourself.  So I'm a bit confused about your report.

You are correct that there is an issue with the example, and it doesn't run as stated.  I have modified the example so that it should now work for you.  As you say, it does have a problem with the main mathjax path, which is set properly for when it is used in its un-packed form (as it would be with the `mathjax-full` package), but it's not correct for the `mathjax` package.  This will be fixed in the next release.

Although there are nearly 300 pages of documentation already, the documentation for use through node is still under construction.  This is a new feature available in version 3, so it all has to be written from scratch.  Version 3 is still a work in progress in many ways.  It was released just a week and a half ago, and there are surely some things to be ironed out.  The examples in the [direct](https://github.com/mathjax/MathJax-demos-node/tree/master/direct#non-component-based-examples) folder of the node demos repository may give you more of an idea about the directory structure while the documentation is being written.

**Comment by ShaMan123** [comment]
Thanks for the reply. 
I didn't know V3 is so fresh, I saw it was released by mistake and tried to implement it and replace `mathjax-node`.
Basically in both `mathjax` and `mathjax-full` a major amount of paths to required files are wrong.
Is V3 compatible with `react-native`?

**Comment by pkra** [comment]
> Is V3 compatible with react-native? I'm trying to implement mathjax in native mobile apps using react-native. V3 seems promising for this task.

I haven't tested it myself but there have been reports on using it in reactive native (especially the SVG output so that you no longer need webviews).

**Comment by ShaMan123** [comment]
This is what I have been doing. 
`mathjax-node` is incompatible with `react-native` so I need a webview to use mathjax, hopefully `V3` is compatible and will remove the need for webview entirely.

**Comment by ShaMan123** [comment]
OK. I managed to make it work.
1. Installed: `npm i mathjax-full`
1. I had to run manually `npm run compile` in the destination dir of `mathjax-full` (i.e. `node_modules/mathjax-full)`

Trying to `import` files directly from `ts` dir isn't possible if using `tsc` myself because then the paths are broken in the output files.

### Suggestion:
 add to `package.json` of the repo:
```diff
  "scripts": {
      ....,
+    "postinstall": "npm run compile"
  },
```

**Comment by ShaMan123** [comment]
It seems that these scripts don't work in my enviroment (Windows)
```
    "copy:mhchem": "npx copyfiles -u 1 'ts/input/tex/mhchem/mhchem_parser*' js",
    "copy:mj2": "npx copyfiles -u 1 'ts/input/asciimath/mathjax2/**/*' js",

```

**Comment by dpvc** [comment]
Try changing these to

```
    "copy:mhchem": "npx copyfiles -u 1 \"ts/input/tex/mhchem/mhchem_parser*\" js",
    "copy:mj2": "npx copyfiles -u 1 \"ts/input/asciimath/mathjax2/**/*\" js",
```

and see if that works.  Apparently windows requires double quotes.

**Comment by ShaMan123** [comment]
I used `fs.copyFileSync` instead.
now V3 compiles and works on `node` and if I require inner modules it work in `react-native`
Thanks for the upgrade!
