### ISSUE TITLE
How can i get the tex which was handled

### ISSUE THREAD

**Issue by yyjjqq94** [mathjax/MathJax-src#359]
component: 'tex-mml-svg' 

i use the typesetPromise to converting the string containing some math , how can i add attribute 'data' on each 'mjx-container'

for example: 
```
content = '$$11111$$example....\\4444\\'

tag1: '<mjx-container data='11111' .........</mjx-container>'

tag2: '<mjx-container data='4444' .........</mjx-container>'
```

or  how can i customize the wrapper to replace the 'mjx-container'?

thx!

**Comment by dpvc** [comment]
Here is one way to get the original TeX into an attribute on the container.  I would not use `data`, as `data` attributes are handled specially on HTML elements.  So I've used `data-tex` in order to comply with the data attribute specification.

Add the following script *before* the script that loads the MathJax component that you are using.

```
<script>
MathJax = {
  options: {
    renderActions: {
      addTeX: [155, (doc) => {
        for (const math of doc.math) {
          math.typesetRoot.setAttribute('data-tex', math.math);
        }
      }, (math, doc) => {
        math.typesetRoot.setAttribute('data-tex', math.math);
      }]
    }
  }
};
</script>
```

This sets up a render action that follows the typesetting (priority 155 is after the typesetting at 150).  It adds the original TeX notation as the `data-tex` attribute.

> how can i customize the wrapper to replace the 'mjx-container'?

Since some of the CSS is based on the container being `mjx-container`, I would not recommend doing that.

**Comment by dpvc** [comment]
Note that this issue tracker is intended for reporting bugs in MathJax.  General questions about MathJax are better asked in the [MathJax User's Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where more people will see it and might be able to offer advice.

**Comment by yyjjqq94** [comment]
> Note that this issue tracker is intended for reporting bugs in MathJax. General questions about MathJax are better asked in the [MathJax User's Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where more people will see it and might be able to offer advice.

ok thx!
