### ISSUE TITLE
Poor performance by using custom tex extension

### ISSUE THREAD

**Issue by woody-li** [mathjax/MathJax-src#361]
I'm using a custom tex extension like https://github.com/mathjax/MathJax-demos-node/tree/master/custom-tex-extension.
It renders by mtext and unicode. 
But it becomes slower and slower by input more and more symbols.
It won't appear by using the non-custom symbols , even input lots of symbols .

**Comment by dpvc** [comment]
Without the actual code you are using, there really isn't much we can say.  But if you arr using symbols that are not in the MathJax fonts, then MathJax will have to measure the characters in order to tell how wide they are when laying out the mathematics, and that requires inserting them into the page and asking the browser to measure the inserted character.  This causes a page reflow, which can be time consuming.  So if you are doing that a lot, that can really slow things down.  It's hard to say for sure without seeing the extension you are using, and the input that you re giving it.

**Comment by woody-li** [comment]
Here's my custom extension code:
`
var Configuration = require('mathjax-full/js/input/tex/Configuration.js').Configuration;
var CommandMap = require('mathjax-full/js/input/tex/SymbolMap.js').CommandMap;

function convertEscapes(text) {
        if (text.indexOf("\\u") === -1) text = "\\u" + text;
        return text.replace(/\\u([0-9A-F]{4})/gi, (match, hex) => String.fromCharCode(parseInt(hex, 16)));
}

var unicodeMap = {
        oiint: "\u222F",
        oiiint: "\u2230",
//...others
};

var mmlMap = new CommandMap("mml", (function (mmlKeys) {
        for (var item in unicodeMap) {
            mmlKeys[item] = ["mml", item];
        }
        return mmlKeys
})({}), {
        mml: function (parser, name, type) {
            var unicode = unicodeMap[type];
            var text = convertEscapes(unicode);
            var symbol = parser.create('node', "mtext", [parser.create('text', text)], {});
            parser.Push(symbol);
        }
});

var mmlConfiguration = Configuration.create('mml', {
        handler: { macro: ['mml'] }
});
`

**Comment by dpvc** [comment]
You don't give the input that you are processing, or which output format you are using, but my (admittedly limited) tests with your extension do not show any significant delay with either CommonHTML or SVG output.

I do note, however, that the characters you are defining are not in the MathJax TeX fonts, and so they will have to be measured in the browser when first used, as I mentioned above.  If there are a lot of different characters, that can cause a delay as each character that is measured will cause a reflow of the page.  I have checked that the caching of the measurements is working, and so only the first time a character is used (in a particular variant and size) will cause a reflow, so that should help with characters that are used multiple times.

If you can put together an example page that exhibits the behavior, I will be happy to take a look at it.

There are a couple of things you could do to reduce some overheard, however.  For example, you could make your CommandMap entries include the converted text itself, rather than just the name of the unicode symbol, and that way you can call the `convertExcapes()` only once, when the symbol is set up rather than every time it is used.  For example

```
var mmlMap = new CommandMap("mml", (function (mmlKeys) {
    for (var item in unicodeMap) {
        mmlKeys[item] = ["mml", convertEscapes(unicodeMap[item])];
    }
    return mmlKeys
})({}), {
    mml: function (parser, name, text) {
        var symbol = parser.create('node', "mtext", [parser.create('text', text)], {});
        parser.Push(symbol);
    }
});
```

Note that `name` will already hold the symbol's name, in case you need that later.

Of course, you can also just use

```
var unicodeMap = {
        oiint: "\u222F",
        oiiint: "\u2230",
//...others
};
```

and avoid the need for `convertEscapes()` entirely.
