### ISSUE TITLE
[Packaging] Publishing typescript-transpiled package on npm

### ISSUE THREAD

**Issue by SylvainCorlay** [mathjax/MathJax-src#384]
I am working on the "Voilà" project which is a tool to turn Jupyter notebooks into standalone apps.

In this context, I want to bundle mathjax 3 in the single webpack bundle for the front-end. Unfortunately, mathjax does not include the transpiled javascript as part of the npm package. Using webpack's `ts-loader` to load the content does not work because internally, import statements include a `js` suffix which prevent the ts-loader from picking it up.

**Comment by SylvainCorlay** [comment]
(Sorry @dpvc I should have brought this up during the NumFOCUS summit).
cc @jasongrout

**Comment by dpvc** [comment]
The compiled js files are in the `mathjax-full` npm package so you could use that if you are using the `mathjax` package now.  The `mathjax` package is set up to be what is on the CDN (since a number of CDN are based on npm packages).  The `mathjax-full` package is for people doing development work with MathJax.

**Comment by SylvainCorlay** [comment]
> The compiled js files are in the mathjax-full npm package so you could use that if you are using the mathjax package now

Yes, this is what I am using, but I only see the `ts` directory in mathjax-full.

**Comment by SylvainCorlay** [comment]
Thanks, I was able to figure it out thanks to your reply.

Closing!.

**Comment by dpvc** [comment]
OK, glad you got it worked out.
