### ISSUE TITLE
Generated configuration is unusable

### ISSUE THREAD

**Issue by Travel9527** [mathjax/MathJax-src#404]
```
MathJax.Hub.Config({
        extensions: ["tex2jax.js"],
        jax: ["input/TeX", "output/HTML-CSS"],
        tex2jax: {inlineMath: [ ['$','$'], ["\\(","\\)"] ],displayMath: [ ['$$','$$'], ["\\[","\\]"] ],processEscapes: true},
        "HTML-CSS": { availableFonts: ["TeX"] },
        TeX: {equationNumbers: {autoNumber: ["AMS"], useLabelIds: true}},
        "HTML-CSS": {linebreaks: {automatic: true}},
        SVG: {linebreaks: {automatic: true}}
    });

config=TeX-AMS-MML_HTMLorMML
```

**Comment by dpvc** [comment]
If you mean the configuration created by the [configuration conversion tool](https://mathjax.github.io/MathJax-demos-web/convert-configuration/convert-configuration.html) produces an error in MathJax v3, that is because your original configuration is also in error.  The 

    autoNumber: ["AMS"]

property should be

    autoNumber: "AMS"

(not an array).  The converter tries to maintain your original values, and so has copied the array to the v3 configuration, as your original configuration indicated.  In version 2, it turns out that the only checks on `autoNumber` where whether it was equal to `"none"` or equal to `"all"` (and anything else defaulted to `"AMS"`, so your incorrect configuration "worked", but only accidentally.  In version 3, the value of the `tags` property (which is the v3 equivalent of `autoNumber`) is used as an index into an array of classes for the various numbering options, and so not using the correct value in v3 leads to an error.  There should be a better error message, however.

In any case, the source of the problem is the error in your original configuration.  If you remove the brackets form the original (or the converted configuration) it should work for you.
