### ISSUE TITLE
Remove file extension from imports in TypeScript files?

### ISSUE THREAD

**Issue by hubgit** [mathjax/MathJax-src#439]
For some reason the TypeScript files are importing from relative paths with '.js' file extensions, which don't exist.

For example, [HTMLAdaptor.ts](https://github.com/mathjax/MathJax-src/blob/master/ts/adaptors/) contains:

```
import {OptionList} from '../util/Options.js';
```

which should(?) be:

```
import {OptionList} from '../util/Options';
```

**Comment by hubgit** [comment]
Closing as I was attempting to use an unusual method of importing the MathJax modules; maybe this is fine.

**Comment by dpvc** [comment]
Just for the record, you are right the no extensions is the usual approach.  The reason we use `.js` is that without them, the Typescript compilation to es5 ends up without the extensions as well (e.g., with just `require('../util/Options')` in your example), and while that works for NodeJS, it doesn't work with other loaders, like SystemJS.  We use SystemJS in our interactive debugging lab, and that wouldn't work without the `.js` extensions (at least not at the time we began work on v3; perhaps new versions of SystemJS would handle it).  Since Typescript handles the compilation fine with the `.js` extensions, we felt this was the best compromise for our situation.
