### ISSUE TITLE
iOS library

### ISSUE THREAD

**Issue by innovateverywhere** [mathjax/MathJax-src#522]
Do you guys have any plans of releasing iOS library. Currently all third party libraries are too old and they are not updating w.r.t. you changes/update. So, it's a humble request to make library for iOS and help us develop beautiful apps in mobile.

Or please let me know if there is some other alternative already you guys have.

Thanks in Advance

**Comment by dpvc** [comment]
We do not provide OS or platform-specific packages for MathJax.  Because MathJax is a javascript library, it can be used in iOS WebView components, so you should be able to include it in Xcode projects that use UIWebView without a special library.  I am not a Mac programmer, so I can't give you more advice than that, but it should work ion the same way that you would load any javascript library into a WebView.

**Comment by pkra** [comment]
With v3, one no longer needs a webview, cf. https://github.com/railsjack/react-native-mathjax-svg

**Comment by dpvc** [comment]
Thanks, Peter.  That is good to know.
