### ISSUE TITLE
AllPackages.ts discrepancy

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#553]
This is more a question but I noticed a discrepancy in AllPackages.ts.

colorv2 and physics are imported and added to the preLoader but not exported. 

Is that intended?

**Comment by pkra** [comment]
Blorg. Another premature posting. Edited with the actual question.

**Comment by dpvc** [comment]
Yes, that is correct.  The colorv2 and color extensions would clash, as they both define \color, and the physics package redefines lots of standard macros (like \sin, \cos, etc.), and so is not included in the AllPackages variable, since that is frequently used to turn on all the extensions.

I suppose it would be possible to have a list of all the extensions, and another one that is the largest reasonable package list, but that's not how it currently is set up.

**Comment by pkra** [comment]
D'oh. That makes perfect sense. Thanks, Davide.
