### ISSUE TITLE
support \mathsfit and \textsfit

### ISSUE THREAD

**Issue by tavin** [mathjax/MathJax-src#667]
I needed `\mathsfit` in my markdown, as available e.g. from the `isomath` package in latex, so here it is.
Also `\textsfit` for completeness. Implemented by https://github.com/mathjax/MathJax-src/pull/666.

**Comment by dpvc** [comment]
Thanks for your interest in contributing to MathJax!

Was it turns out, this issue has been under discussion in mathjax/MathJax#2595, and there is a recent PR (#676) that handles this in a more general way, and that includes all the `\mathNN` (as well as `\symNN`) macros.  So while we appreciate the contribution, we won't be merging this particular request.
