### ISSUE TITLE
Rollup not happy with __dirname

### ISSUE THREAD

**Issue by edemaine** [mathjax/MathJax-src#795]
I see from #420 that some Rollup compatibility is maybe desired.  I was just trying to port [my Web Worker application of MathJax](https://github.com/edemaine/tex2svg-webworker) from Webpack to Rollup.  I noticed that [Loader](https://github.com/mathjax/MathJax-src/blob/master/ts/components/loader.ts) uses `__dirname` which is supported by Webpack but apparently not Rollup:

https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/components/loader.ts#L202-L203

In my case, I'm [preloading all modules I want](https://github.com/edemaine/tex2svg-webworker/blob/main/tex2svg.coffee), so I don't really want to activate the Loader at all, except to initialize the `preLoad` list.  Is there some way to bypass this? Maybe I should use [direct mode](https://docs.mathjax.org/en/latest/server/direct.html)?

I'm also not sure rollup is the best approach; it sadly doesn't seem to end up with smaller bundles. So probably not a high priority thing.

**Comment by dpvc** [comment]
It looks like you have already converted to direct mode, so that should resolve the problem for you.  You don't need the MathJax configuration object any longer, as that is only used by the `startup` and `loader` modules, which you aren't using.  So the code

https://github.com/edemaine/tex2svg-webworker/blob/985dd617969dfc980baac1904425b9d0c9322eee/tex2svg.coffee#L49-L61

can be removed.

Alternatively, you could probably have used the original approach, by replacing

https://github.com/edemaine/tex2svg-webworker/blob/d80d9942b462a2cea9fde3d6fee64a427fc9e4d4/tex2svg.coffee#L11

with 

``` js
require("mathjax-full/js/components/global.js");
```

https://github.com/edemaine/tex2svg-webworker/blob/d80d9942b462a2cea9fde3d6fee64a427fc9e4d4/tex2svg.coffee#L19

by

``` js
require("mathjax-full/js/components/startup.js");
```

and deleting

https://github.com/edemaine/tex2svg-webworker/blob/d80d9942b462a2cea9fde3d6fee64a427fc9e4d4/tex2svg.coffee#L21-L22

though I haven't tested it to make sure.  In any case, it could have been worked out, but if you are not planning to use any of the loader functionality, there is not much reason to use the components approach.  The direct calls are the better approach, where, I would say.

**Comment by edemaine** [comment]
Many thanks, in particular for spotting that stray code! I confirmed that the direct port indeed works fine on Rollup. So, problem solved!
