### ISSUE TITLE
AsciiMath not found (npm module)

### ISSUE THREAD

**Issue by stnor** [mathjax/MathJax-src#85]
Hi,
I'm trying to fire up mathjax3 using the npm package for alpha-3.

```
import {MathJax} from "mathjax3/mathjax3/mathjax";
import "mathjax3/mathjax3/handlers/html";
import {AsciiMath} from "mathjax3/mathjax3/input/asciimath";
import {CHTML} from "mathjax3/mathjax3/output/chtml";
```

I'm getting the following error:
client:167 ./node_modules/mathjax3/mathjax3/input/asciimath.js
Module not found: Error: Can't resolve '../../mathjax2/input/AsciiMath.js' in '/Users/stnor/devel/src/nomp/frontend/nomp/node_modules/mathjax3/mathjax3/input'
 @ ./node_modules/mathjax3/mathjax3/input/asciimath.js 38:21-65

Seems like asciimath is not included in the mathjax2 folder, only the css.

**Comment by dpvc** [comment]
The AsciiMath input tax hasn't been converted to the v3 structure yet, so it calls on the legacy version 2 code.  Unfortunately, that code was left out of the npm alpha version (by a too-aggressive `.npmignore` file that leaves out all the v2 input jax, instead of leaving the AsciiMath one in place).

You can download the `[mathjax2/input/AsciiMath.js](https://github.com/mathjax/mathjax-v3/tree/master/mathjax2/input)` and that should clear up your issue.

**Comment by stnor** [comment]
Thanks.

I opted to use ascii2math instead, as it was available as an es6 module.

/Stefan

**Comment by dpvc** [comment]
AsciiMath has been included (but currently with legacy code) in the 3.0.0 release.
