### ISSUE TITLE
v4: DefaultFont.js not CJS

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#866]
Both the npm package and local compilation leave me with `js/output/svg|html/DefaultFont.js` as ESM, e.g.,

```
export {MathJaxModernFont as DefaultFont} from 'mathjax-modern-font/js/output/fonts/mathjax-modern/svg.js';
export const fontName = 'mathjax-modern';
```

This causes issues for me in nodejs:

```
.../node_modules/mathjax-full/js/output/svg/DefaultFont.js:1
export {MathJaxModernFont as DefaultFont} from 'mathjax-modern-font/js/output/fonts/mathjax-modern/svg.js';
^^^^^^

SyntaxError: Unexpected token 'export'
```

Rewriting this to CJS manually seems to fix things.

**Comment by dpvc** [comment]
Duplicate of mathjax/MathJax#2944.

You should be able to use `node -r esm' to run the application so that it handles this file.  The `DefaultFont.js` file is a stop-gap measure that fixes an issue that came up at the last minute when putting 4.0.0-alpha together, and I hope to have a better solution for the official release.

**Comment by pkra** [comment]
Oh, I missed that. Unfortunately, `node -r esm` won't help me. I'll comment there.
