### ISSUE TITLE
SVG StyleList unused styles?

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-src#874]
The styles for the SVG output include `.mjx-dashed` and `.mjx-dotted`:

https://github.com/mathjax/MathJax-src/blob/2911de7ab7d11861805f7ff3bfc1a27e6406d553/ts/output/svg/Wrappers/mtable.ts#L113-L119

Since I couldn't find any content with either class on the AMS end, I looked where these classes might get added - and didn't find anything. It looks like `addBorderBroken` does the job of handling these borders.

https://github.com/mathjax/MathJax-src/blob/f939f2ff2c4678785e9bf3d3b17e8c6151f0ce9c/ts/output/svg/Wrapper.ts#L272-L274

Perhaps the classes are leftovers from v2 or there was a later change or (more likely) I didn't spot where these classes are actually used.

**Comment by dpvc** [comment]
These are used for the lines within a matrix (from the `rowlines` and `columnlines` attributes of `mtable`), and are created in the `lineClass()` function

https://github.com/mathjax/MathJax-src/blob/8565f9da973238e4c9571a86a4bcb281b1d98d9b/ts/output/svg/Wrappers/mtable.ts#L241-L243

It constructs the class name dynamically, which is why searching for `mjx-dashed` or `mjx-dotted` won't find it.

This method is used in the `makeFrame()`, `makeVLine()`, and `makeHLine()` methods that follow it.

**Comment by pkra** [comment]
Thanks for clarifying!

**Comment by pkra** [comment]
Just to follow up and more FYI.

Looking at `lineClass`, I noticed (from AMS content) that this generates one class name (mjx-solid) that has no declaration in StyleList. So IIUC since authors could specify random attributes, this generates random class names, but only dotted and dashed do anything. I guess that's nice for authors who want to add custom styles.

This reminds me that in AMS content I found that the complex selectors in StyleList never matter (to the content), except for the overflow related one (which we actually replace with a helper class). Now it looks there's also always a class; that's nice (unless mjx-solid is likely to be removed). 

I also noticed that data-line has two different attribute values that are never used (and data-frame doesn't really need "true" either). So switching to mjx-solid offers additional opportunities to clean up bloat in post - which is nice.

I realize I'm playing with fire but for SVG this has worked out well over the past few years.
